version : "3"
services:
  mongodb:
    image : mongo:4.4-bionic

    networks:
      - surge
    volumes:
      - data:/data/db
  server:
    image: api-server
    build: ./server/
    ports:
      - "8060:8060"
    networks:
      - surge
    volumes:
      - ./server/:/usr/src/app
      - /server/node_modules
    depends_on:
      - mongodb
    
  client:
    image: react-app
    build: ./client/
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - surge
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
networks:
  surge:
    driver: bridge
volumes:
  data:
    driver: local
  logs:

